### ISSUE TITLE
`getInitialProps` is cached, not updated.

### ISSUE THREAD

**Issue by zynkn** [danielcondemarin/serverless-next.js#268]
**Describe the bug**
I am getting some data from my DB in `getInitialProps`.
When I changed my DB data, `getInitialProps` didn't catch the changed data.

**To Reproduce**

````
MyPage.getInitialProps = async (props) => {
  try{
    const { data } = await axios.get('MY_API_URL').catch((e)=>{ throw e });
    if(data.isPublished) return { data };
    else throw data;
  }catch(e){
    return { ...e }
  }
}
````
This issue occurs in `production`.
This code is working even I changed `isPublished` to `false`.
I mean, 

At the first, I set up the `isPublished` to `false`.
I entered the Web, I can see `Error Page`.

and then, I changed the `isPublished` to `true`.
I entered the Web, I can see `MyPage`.

and, I changed again to `false` the `isPublished`.
I entered the Web, I can still see `MyPage`. 

**Expected behavior**
I want to remove the cached data in `getInitialProps`

What I am missing?

**Comment by danielcondemarin** [comment]
@zynkn This should be fixed in the latest version @1.7.3 of the project. You mind testing using that? The TTL before was set to 5 seconds which means you'd get cached responses from ssr pages. That's now been changed to 0 so is not cached anymore.

**Comment by zynkn** [comment]
> @zynkn This should be fixed in the latest version @1.7.3 of the project. You mind testing using that? The TTL before was set to 5 seconds which means you'd get cached responses from ssr pages. That's now been changed to 0 so is not cached anymore.

**Comment by zynkn** [comment]
@danielcondemarin This issue still presents. I've edited my data in DB but it doesn't update them.

**Comment by zynkn** [comment]
It works.
